version: '3.8'

services:
  gcs-dev:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces:cached

    ports:
      - "5173:5173" # React frotend server
      - "8080:8080" # Go backend server

    command: sleep infinity